### ISSUE TITLE
Can't get any result

### ISSUE THREAD

**Issue by lorenzoromani1983** [pielco11/TOT#1]
Hi.
I installed DOT on my maltego CE, but i can't get any result.
tried with many onion services.
Can you provide me with an url that is currently giving results?
So I can check if i am getting it wrong.

thankx

**Comment by pielco11** [comment]
Hi @lorenzoromani1983,

I can guarantee that all services are up and running. Hidden Services have `maltego.OnionService` entity type, which is shipped with the transform itself, so importing the transform will import this entity as well.

Search in the `Entity Palette` for "onion service", then drag the icon and so change `Onion Service` field.

I added some url into `all_http.txt` file, a filtered list is in `async/200.txt` file.

![immagine](https://user-images.githubusercontent.com/17363750/45355800-a1a41200-b5c1-11e8-8839-72fdd452858c.png)

**Comment by pielco11** [comment]
If you get some kind of error, don't hesitate to point me out. (behaviour not expected)
